# .github/workflows/scheduled-run.yml
name: Scheduled Caller

on:
  schedule:
    - cron: '0 6 * * *' # every day at 06:00 UTC
  workflow_dispatch:      # Optional: manual trigger

permissions:
  contents: write
  id-token: write
  actions: write
  packages: write
  pull-requests: write
  issues: write
  statuses: write
  # Add other permissions if required by the reusable workflow

jobs:
  call-reusable:
    uses: to0drunk/revanced_auto_builds/.github/workflows/build.yml
